### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by infernoshoot** [abrasic/abratools#1]
Unable to instal
![88](https://user-images.githubusercontent.com/29793108/155061713-07e83b84-cb38-4c2d-b221-94d78730243e.PNG)
l

**Comment by abrasic** [comment]
Hi there, thanks for your report, and I sincerely apologize for the problems you're facing.

However I was able to reproduce your problem on blender 3.1 and applied a fix to the main branch. Try downloading it again.

**After installing the addon,** please rename the folder located in `C:\Users\[you]\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons` from `abratools-main` to `abTools` as a temporary fix -- as this is another issue with the script looking for the specific name `abTools` folder. I'll be sure to apply this fix in a later release.

Let me know if the above solutions worked for you, and I'll leave this issue open until I get the time to fully fix the issue

Cheers

EDIT: Should be fixed in alpha3. I will fix the repo eventually so the desired file hierarchy is the same in the releases download. Please download from the Releases page instead. If you encounter any further issues please let me know
