### ISSUE TITLE
AbraTools crash on Frame Range to Selection with no curves selected.

### ISSUE THREAD

**Issue by AsaTheUncle** [abrasic/abratools#2]
![image](https://github.com/abrasic/abratools/assets/41550157/7eeda309-9e75-41a9-a5c3-a4dba8824067)

When a rig control is selected with no curves highlighted, pressing the "Frame Range to Selection" button on the shelf causes AbraTools to crash, leaving the AbraTools editor type and returning to Graph Editor editor type. 

![image](https://github.com/abrasic/abratools/assets/41550157/83784a1b-5c67-49ca-94a7-f340cb0f1c5d)
-turns into-
![image](https://github.com/abrasic/abratools/assets/41550157/d7fa3417-5e08-4699-9831-97fb5ac805b6)

Pressing aT button in the viewport creates another editor window, relaunching the aT shelf, but also leaving a duplicate editor window.

**Comment by abrasic** [comment]
Hello,

Thank you very much for your report. The bug regarding Frame Range to Selection has been confirmed and appears to have been fixed.

> Pressing aT button in the viewport creates another editor window, relaunching the aT shelf, but also leaving a duplicate editor window.

This is the expected result. When you click the "aT" icon on the viewport it checks for any areas with a "Preferences" type in the active window. Otherwise, it will automatically create a new Preferences area of itself under the viewport it was called in. In your case it created a new area, because the said area crashed while it was stuck in the Graph Editor context, it does not detect any Preferences area.
