### ISSUE TITLE
3D Viewport crash when using Go to keyframe

### ISSUE THREAD

**Issue by AsaTheUncle** [abrasic/abratools#3]
Python: Traceback (most recent call last):
  File "C:\Users\barte\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\abratools\core\quickView.py", line 290, in execute
    curve.keyframe_points[len(curve.keyframe_points)-1].select_control_point = True
IndexError: bpy_prop_collection[-1]: out of range.

When in 3D viewport, using a hotkey to access Go to keyframe with an NLA Strip Control selected in Graph editor, causes the viewport to crash.

**Comment by abrasic** [comment]
Hello, and thanks again for your report. I have confirmed this error and seems to have been fixed.

This appears to have been caused because your _Animated Influence_/_Animated Strip Time_ F-Curves had no keyframes on them. A lot of the tools assume that at least a single key should make up an F-Curve but is odd that the NLA Control 'curves' continue to exist in the timeline despite them having no keys. Regardless I've added handling to prevent that error from happening.

More tools could be affected by the same condition, a temporary workaround would be to make sure that your NLA Strip Control F-Curves have at least a single key on them.
